name: Sync Docker Images

on:
  push:
    paths:
      - 'images.txt'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Log in to Target Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Sync Docker Images
      run: |
        # Read all images from images.txt
        IMAGES=$(cat images.txt)

        # Loop over each image and pull/push it
        for image in $IMAGES; do
          echo "Processing $image"
          docker pull $image
          docker tag $image ${{ secrets.REGISTRY_URL }}/$image
          docker push ${{ secrets.REGISTRY_URL }}/$image
        done

    - name: Log out from DockerHub
      run: docker logout

    - name: Log out from Target Registry
      run: docker logout ${{ secrets.REGISTRY_URL }}
