name: Sync Docker Images

on:
  push:
    paths:
      - 'images.txt'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Log in to Target Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Sync Docker Images
      run: |
        # Read all image mappings from images.txt
        while IFS=' -> ' read -r src_image dest_image; do
          if [ -n "$src_image" ] && [ -n "$dest_image" ]; then
            echo "Processing $src_image -> $dest_image"
            docker pull "$src_image"
            docker tag "$src_image" "$dest_image"
            docker push "$$dest_image"
          fi
        done < images.txt

    - name: Log out from DockerHub
      run: docker logout

    - name: Log out from Target Registry
      run: docker logout ${{ secrets.REGISTRY_URL }}
